version: '3.8'

services:
  app:
    build: .
    container_name: auth-backend
    ports:
      - "8080:8080"
    depends_on:
      - usuario
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://usuario:5432/usuario
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: admin
    networks:
      - usuario-net

  usuario:
    image: postgres:16
    container_name: usuario
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: usuario
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
    volumes:
      - usuario-data:/var/lib/postgresql/data
    networks:
      - usuario-net

networks:
  usuario-net:

volumes:
  usuario-data:
